[package]
name = "ch07-04-mod-use"
version = "0.1.0"
authors = ["yhnu <buutuud@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"